services:
  - type: web
    name: tds-rag-api
    env: python
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
